[package]
name = "rust-linked-lists"
version = "0.1.0"
authors = ["Maksim Kudrautsau <maksim.kudrautsau@codex-soft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
